version: '3.4'

services:
  facesapi2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  faces.webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  ordersapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

